Movies_Review/auth.py
""" Routes for user authentication """
from flask import Blueprint, url_for, render_template, request, redirect, flash
from flask_login import current_user, login_user, logout_user, login_required
from .forms import SignupForm, LoginForm
from .models import db, User
from .import login_manager

# Blueprint Configuration
auth_bp = Blueprint(
    'auth_bp', __name__,
    template_folder='templates',
    static_folder='static'
)

@auth_bp.route("/signup", methods=["GET", "POST"])
def signup():
    """
    User sign-up page.
    GET requests serve sign-up page.
    POST requests validate form & user creation.
    """
    form = SignupForm()
    if form.validate_on_submit():
        # Users fill form correctly
        # Check if email already exists
        existing_user = User.query.filter_by(email=form.email.data).first()
        if existing_user is None:
            # Check if username already exists
            existing_username = User.query.filter_by(username=form.username.data).first()
            if existing_username is None:
                user = User(username=form.username.data, 
                            email=form.email.data, 
                            password=form.password.data)
                db.session.add(user)
                db.session.commit() # Create new user
                login_user(user) # Log in as newly created user - magically!
                # Go to movie search page
                return redirect(url_for('main_bp.search'))
            flash("Username already exists!")
        else:
            flash("A user already exists with that email address.")
    return render_template("signup.html", form=form)

@auth_bp.route("/", methods=["GET", "POST"])
def login():
    """
    Log-in page for registered users
    GET requests serve log-in page.
    POST requests validate and redirect user to search page
    """
    # Bypass if user is already logged in 
    if current_user.is_authenticated:
        return redirect(url_for('main_bp.search'))

    form = LoginForm()
    # Validate login attempt
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        # If user exists in our database and password matches
        if user and user.password == form.password.data:
            login_user(user) # Log in as existing user
            return redirect(url_for('main_bp.search'))
        elif not user:
            flash("Account does not exists!")
        else:
            flash("Password does not match!")
    return render_template("login.html", form=form)

@auth_bp.route("/logout")
@login_required
def logout():
    """ User log-out logic. """
    logout_user()
    return redirect(url_for('auth_bp.login'))

# Given *user_id*, return the associated User object. 
# Also, we can access current user info via current_user.attribute
@login_manager.user_loader
def load_user(user_id):
    """ Check if user is logged-in on every page load. """
    if user_id:
        return User.query.get(user_id)
    return None

@login_manager.unauthorized_handler
def unauthorized():
    """ Redirect unauthorized users to Login page. """
    flash("You must be logged in to view that page")
    return redirect(url_for('auth_bp.login'))

Movies_Review/templates/layout.html
<!DOCTYPE html>
<html>
    <head>
        <!-- Required meta tags -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
        <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@300;400;700&display=swap" rel="stylesheet">
  
        {% block pagestyles %}{% endblock %}
        <title>{% block title %}{% endblock %}</title>
    </head>
    <body>
        {% block body %}
        {% endblock %}
        
        <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
    </body>
</html>

Movies_Review/templates/login.html
{% extends "layout.html" %}

{% block pagestyles %}
      <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='dist/css/home.css')}}">
{% endblock %}

{% block title %} Account Login - Moviebia {% endblock %}

{% block body %}
<div id="alert">
    {% for message in get_flashed_messages() %}
        <div class="alert alert-warning">
            <button type="button" class="close" data-dismiss="alert">&times;</button>
            {{ message }}
        </div>
    {% endfor%}  
</div>

<form action="{{ url_for('auth_bp.login') }}" method="post">
    <h3>Log In</h3>
    <hr>

    {{ form.csrf_token }}

    <fieldset class="form-group email">
        {{ form.email.label }}
        {{ form.email(class="form-control", placeholder='youremail@example.com') }}
        {% if form.email.errors %}
            <ul class="errors" style="color: red">
                {% for error in form.email.errors %}
                    <li>{{  error }}</li>
                {% endfor %}
            </ul>
        {% endif %}
    </fieldset>  

     <fieldset class="form-group password">
        {{ form.password.label }}
        {{ form.password(class="form-control", placeholder='Enter password') }}
        {% if form.password.errors %}
            <ul class="errors" style="color: red">
                {% for error in form.password.errors %}
                    <li>{{  error }}</li>
                {% endfor %}
            </ul>
        {% endif %}
    </fieldset>  

    {{ form.submit(class="btn btn-primary btn-block") }}

    <small id="emailHelp" class="form-text text-muted">Don't have an account? <a href="{{ url_for('auth_bp.signup') }}">Sign up.</a></small>
</form>
{% endblock %}

Movies_Review/templates/movie.html
{% extends "layout.html" %}

{% block pagestyles %}
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='dist/css/info.css')}}">
{% endblock %}

{% block title %} {{ movie_info['title'] }} Reviews - Moviebia {% endblock %}

{% block body %}
    <div class="d-flex flex-column container-fluid" id="movieStyle">
        <div class="divTextStyle">
            <h1 style="text-align: center;" class="text-white"> {{ movie_info['title'] }} </h1>
        </div>
        <div class="d-flex flex-column">
            <!-- Check if image is available -->
            {% if movie_info['backdrop_path'] %}
                <img src="http://image.tmdb.org/t/p/w780/{{ movie_info['backdrop_path'] }}" class="image_center">
            {% else %}
                <img src=" {{ url_for('static', filename='dist/img/noimage.png') }} " class="image_center">
            {% endif %}
            
            <div class="card" style="width: 50%; align-self: center;">
                <div class="card-body">
                    <h5 class="card-title text-center">Overview</h5>
                    <p class="card-text">{{ movie_info['overview'] }}</p>
                </div>
            </div>
        </div>

        <h3 style="text-align: center; margin-top: 50px;" class="text-white">User reviews</h3>

        <form id="review" action="{{ url_for('main_bp.movie', movie_id=movie_info['id'], movie_title=movie_info['title']) }}" method="post" class="text-center border border-light p-5" style="width: 900px; align-self: center; height: 200px;">
            {{ form.csrf_token }}
            <fieldset> {{ form.rating(class="form-control mr-sm-2") }} </fieldset>
            <fieldset> {{ form.text(class="form-control mr-sm-2", placeholder="Type your review here") }} </fieldset>
            {{ form.submit(class="btn btn-outline-success btn-rounded btn-sm my-0 mt-2 mb-5 text-right") }}
        </form>
        <hr>

        {% for review in reviews %}
            <div class="card bg-light border-dark mb-3 row" style="align-self: center; width: 900px;">
                <div class="card-header"> <h4> Username: {{ review.author }}</h4></div>
                <div class="card-body">
                    <h5 class="card-title"> Grade: {{ review.rating }} </h5>
                    <p class="card-text"> {{ review.text }} </p> 
                    <span id="time"> Review Date: {{ review.timestamp.strftime('%m-%d-%Y') }} </span>
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock %}

Movies_Review/templates/movies.html
{% extends "layout.html" %}

{% block title %} {{ query }} Reviews - Moviebia {% endblock %}

{% block body %}
    {% if results %}
        <table class="table table-bordered" style="background-color: #D8BFD8">
            <thead class="text-white" style="background-color: #212121">
                <tr>
                    <th>Poster</th>
                    <th>Title</th>
                    <th>Metascore</th>
                    <th>Released Date</th>
                </tr>
            </thead>
            <tbody>
                {% for result in results %}
                    <tr>
                        <td><img src="http://image.tmdb.org/t/p/w185/{{ result['poster_path'] }}"></td>
                        <td><a href="{{ url_for('main_bp.movie', movie_id=result['id'], movie_title=result['title']) }}">{{ result['title'] }}</a></td>
                        <td>{{ result['vote_average'] }}</td>
                        <td>{{ result['release_date'] }}</td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    {% else %}
        <p>Sorry, No results found!</p>
    {% endif %}
{% endblock %}

Movies_Review/templates/search.html
{% extends "layout.html" %}

{% block pagestyles %}
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='dist/css/search.css')}}">
{% endblock %}

{% block title %} Movie Reviews - Moviebia {% endblock %}

{% block body %}
<div id="header">
    <h1>Search Engine</h1>
    <form action="{{ url_for('auth_bp.logout') }}" method="get"><button class="btn btn-outline-warning btn-md">Log out</button></form>
</div>

<div id="alert">
    {% for message in get_flashed_messages() %}
        <div class="alert alert-warning">
            <button type="button" class="close" data-dismiss="alert">&times;</button>
            {{ message }}
        </div>
    {% endfor%}  
</div>

<div id="content">
    <h5> Search your favorite movie here</h5>
    <form action="{{ url_for('main_bp.search') }}" method="post" class="form-inline text-center">
        {{ form.csrf_token }}
        
        <fieldset>
            {{ form.query(class="form-control mr-2", placeholder="Enter movie title") }}
        </fieldset>

        {{ form.submit(class="btn btn-warning btn-sm") }}
    </form>

    <div id="copyright">
        <p> Copyright @ 2020 Tu Vu, Duong Nguyen, University of Texas at Dallas </p>
        <p> All rights reserved </p>
    </div>
</div>
{% endblock %}

Movies_Review/templates/signup.html
{% extends "layout.html" %}

{% block pagestyles %}
      <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='dist/css/home.css')}}">
{% endblock %}

{% block title %} Account Login - Moviebia {% endblock %}

{% block body %}
<div id="alert">
    {% for message in get_flashed_messages() %}
        <div class="alert alert-warning">
            <button type="button" class="close" data-dismiss="alert">&times;</button>
            {{ message }}
        </div>
    {% endfor%}  
</div>

<form action="{{ url_for('auth_bp.signup') }}" method="post" id="signup" class="auth-inner">
    <h3>Sign Up</h3>
    <hr>
    
    {{ form.csrf_token }}

    <fieldset class="form-group username">
        {{ form.username.label }}
        {{ form.username(class="form-control", placeholder = 'John Smith') }}
        {% if form.username.errors %}
            <ul class="errors" style="color: red">
                {% for error in form.username.errors %}
                    <li>{{  error }}</li>
                {% endfor %}
            </ul>
        {% endif %}
    </fieldset>  

    <fieldset class="form-group email">
        {{ form.email.label }}
        {{ form.email(class="form-control", placeholder='youremail@example.com') }}
        {% if form.email.errors %}
            <ul class="errors" style="color: red">
                {% for error in form.email.errors %}
                    <li>{{  error }}</li>
                {% endfor %}
            </ul>
        {% endif %}
    </fieldset>  

     <fieldset class="form-group password">
        {{ form.password.label }}
        {{ form.password(class="form-control", placeholder='Enter password') }}
        {% if form.password.errors %}
            <ul class="errors" style="color: red">
                {% for error in form.password.errors %}
                    <li>{{  error }}</li>
                {% endfor %}
            </ul>
        {% endif %}
    </fieldset>  

     <fieldset class="form-group confirm">
        {{ form.confirm.label }}
        {{ form.confirm(class="form-control") }}
        {% if form.confirm.errors %}
            <ul class="errors" style="color: red">
                {% for error in form.confirm.errors %}
                    <li>{{  error }}</li>
                {% endfor %}
            </ul>
        {% endif %}
    </fieldset>

    {{ form.submit(class="btn btn-primary btn-block") }}

    <small id="emailHelp" class="form-text text-muted">Already have an account? <a href="{{ url_for('auth_bp.login') }}">Log in.</a></small>
</form>
{% endblock %}